[package]
name = "exporter"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-native-tls", "macros", "runtime-tokio-rustls", "chrono"] }
anyhow = "1.0.99"